---
homebrew_packages:
  - ansible
  - asdf
  - aws-vault
  - awscli
  - gh
  - git
  - neovim
  - rcm
  - ripgrep
  - starship
  - terraform
  - tmate
  - tmux

homebrew_cask_packages:
  - 1password
  - font-fira-code-nerd-font
  - google-chrome
  - grammarly-desktop
  - iterm2
  - rectangle
  - session-manager-plugin
  - slack
  - spotify
