---
- name: "List installed plugins"
  ansible.builtin.command: asdf plugin list
  register: asdf_plugin_list

- name: "Declare installed and expected plugins"
  set_fact:
    installed_plugins: "{{ asdf_plugin_list.stdout_lines }}"
    expected_plugins: "{{ asdf_plugins.keys() }}"

- name: "Declare untracked plugins"
  set_fact:
    untracked_plugins: "{{ installed_plugins | difference(expected_plugins) }}"

- name: "Remove untracked plugins"
  ansible.builtin.command: "asdf plugin remove {{ item }}"
  loop: "{{ untracked_plugins }}"

- name: "Add plugins"
  ansible.builtin.command: "asdf plugin add {{ item.key }} {{ item.value.git_url | default }}"
  args:
    creates: "{{ asdf_dir }}/plugins/{{ item.key }}"
  with_dict: "{{ asdf_plugins }}"

- name: "Install plugins dependencies"
  community.general.homebrew:
    name: "{{ item.value.dependencies }}"
  when: item.value.dependencies is defined
  with_dict: "{{ asdf_plugins }}"
