# vi: ft=yaml.ansible
---
- name: "List installed plugins"
  ansible.builtin.command: asdf plugin list
  register: asdf_plugin_list

- name: "Declare installed and required plugins"
  set_fact:
    installed_plugins: "{{ asdf_plugin_list.stdout_lines }}"
    required_plugins: "{{ asdf_plugins.keys() }}"

- name: "Declare untracked plugins"
  set_fact:
    untracked_plugins: "{{ installed_plugins | difference(required_plugins) }}"

- name: "Remove untracked plugins"
  ansible.builtin.command: "asdf plugin remove {{ item }}"
  loop: "{{ untracked_plugins }}"

- name: "Add plugins"
  ansible.builtin.include_tasks: plugin.yml
  with_dict: "{{ asdf_plugins }}"
